---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsalert
  namespace: monitor-sa
  labels:
    app: smsalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smsalert
  template:
    metadata:
      labels:
        app: smsalert
    spec:
      containers:
        - name: smsalert
          image: appiaim-registry.cn-zhangjiakou.cr.aliyuncs.com/ssc-monitor/smsalert:v1.2
          args:
            - "--config.file=/etc/app/configmap-smsalert-dbconfig.yml"
          volumeMounts:
            - name: config
              mountPath: "/etc/app"
          ports:
            - name: http
              containerPort: 5000
      volumes:
        - name: config
          configMap:
            name: db-config
      imagePullSecrets:
        - name: ssc-monitor-secret


#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 5000
#          initialDelaySeconds: 10
#          periodSeconds: 10
#
#        readinessProbe:
#          httpGet:
#            path: /readyz
#            port: 5000
#          initialDelaySeconds: 5
#          periodSeconds: 5
#
#        startupProbe:
#          httpGet:
#            path: /startup
#            port: 5000
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: smsalert
  namespace: monitor-sa
  labels:
    app: smsalert
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: smsalert